### ISSUE TITLE
segfaults on fedora tests

### ISSUE THREAD

**Issue by niktre** [espressopp/buildenv#19]
@jkrajniak @junghans shouldn't we install `python2-numpy` as well, in addition to all the other packages? 

I installed fedora on my laptop, compiled ESPResSo++ and `h5py` was missing, so most tests failed. When I installed it, additional packages were installed as well: `atlas`, `hdf5`, `liblzf`, `python-six`, `python2-h5py`, `python2-nose` and `python2-numpy`. When these were installed, I had no problems running tests.

**Comment by junghans** [comment]
Seems reasonable, just make a PR to add these packages to both Fedora Dockerfiles.

**Comment by junghans** [comment]
Obsolete.
